#!/bin/bash

GITURL=https://github.com/Biggybi/dotfiles
SRC=~/.dotfiles
DST=~
FILES=".vimrc\
	.bashrc\
	.bash_aliases"

if [ -d $SRC ]
then
	echo "Not cloning : $SRC exists"
else
	git clone $GITURL $SRC
fi
for f in $FILES
do
	if [ -e $SRC/$f ]
	then
		if [ -L $DST/$f ]
		then
			rm $DST/$f
		fi
		ln -s $SRC/$f $DST
		echo file linked : $f
	else
		echo not a file  : $f
	fi
done
