#!/bin/bash

GITURL=https://github.com/Biggybi/dotfiles
SRC=~/.dotfiles
DST=~
BACKUP=~/.dotfiles/dots_back
FILES=(.bin\
	.vim\
	.vimrc\
	.bashrc\
	.bash_aliases)

# use same names for links as in FILES
LINK=$FILES
# set different link names if needed
# LINK=(.bin\
# 	.link1
# 	.link2
# 	.link3
# 	.link4)

#for Mac OS
if [[ "$OSTYPE" == "darwin"* ]]
then
	LINK=(.bin\
		.vim\
		.vimrc\
		.bash_profile\
		.bash_aliases)
fi

if [ -d $SRC ]
then
	echo "Not cloning : $SRC exists"
else
	git clone $GITURL $SRC
fi

i=0
for f in "${FILES[i]}"
do
	echo $i
	l=${LINK[i]}
	if [ -e $SRC$l ]
	then
		if [ -L $DST$l ]
		then
			rm $DST$l
			echo "link deleted : $DST$l"
		elif [ -f $DST$l ]
		then
			mv $DST$l $SRC$BACKUP
			echo "file saved : $SRC$BACKUP $l"
		elif [ -d $DST/$l ]
		then
 			mv $DST$l $BACKUP$l
			echo "repertory saved : $BACKUP$l"
		fi
		ln -sf $SRC$f $DST$l
		echo "link created : $l -> $f "
	else
		echo "no such file : $l"
	fi
	let i=i+1
done
