#!/bin/bash

# links files from DOTS to their provided LOCFILES

GITURL=https://github.com/Biggybi/dotfiles
SRC=$HOME/dotfiles
# DST=$HOME
DST=/tmp/dot
BACKUP=$HOME/dotfiles/dots_back

cd $SRC

# git files to link
DOTFILES=(vim
	vimrc
	bashrc
	bash_aliases
	inputrc
	bin
	git_template
	fonts
	zshrc
	neomuttrc)

# links to create localy for Linux
LOCFILES=(.vim
	.vimrc
	.bashrc
	.bash_aliases
	.inputrc
	bin
	.git_template
	.fonts
	.zshrc
	.config/neomutt/neomuttrc)

# links to create localy for Mac
if [[ "$OSTYPE" == "darwin"* ]]
then
	LOCFILES=(vim
		.vimrc
		.bashrc
		.bash_aliases
		.inputrc
		bin
		.git_template
		.fonts
		.zshrc)
fi

if [ -d "$SRC" ]
then
	echo "Not cloning : $SRC exists"
else
	git clone $GITURL $SRC
fi

let PLUGIN=0
let COPY=0

while [[ $1 == -* ]]
do
	echo param = $1
	if [ "$1" == "--git" ] || [ "$1" == "-g" ] || [ "$1" == "--plugins" ]
	then
		PLUGIN=1
	shift
	fi
	if [ "$1" == "--hard" ] || [ "$1" == "--cp" ] || [ "$1" == "-h" ]
	then
		COPY=1
	shift
	fi
done

if [ $COPY == 1 ]
then
	echo "Copy mode"
else
	echo "Link mode (use \`-c\` to hard-copy)"
fi

if [ $PLUGIN == 1 ]
then
	echo "Plugin will be downloaded"
else
	echo "Plugin won't be downloaded (use \`-g\` to get plugins)"
fi

if [ $PLUGIN == 1 ]
then
	cd "${DST}/${LOCFILES[0]}"
	git submodule init
	git submodule update
fi

i=0
# while [ -d "$BACKUP" ] && [ ! -f "$BACKUP/.dots_back" ]
# do
# 	let i=i+1
# 	echo "$BACKUP exists, new backup dir"
# 	BACKUP="$BACKUP$i"
# 	echo "$BACKUP new backup dir"
# done

# [ ! -d "$BACKUP" ] && mkdir "$BACKUP"
# [ -d "$BACKUP" ] && touch "$BACKUP/.dots_back"
# mv "$DST/$l" "$BACKUP/$l"

i=0
for f in "${DOTFILES[@]}"
do
	l="${LOCFILES[i]}"
	echo "$i $l"
	# cmp -s "$SRC/$f" "$DST/$l" 2> /dev/null
	if [ $? -eq 1 ] && [ -n "$l" ] && [ -e "$DST/$l" ]
	then
		echo "go backup"
		lback=$l
		if [ -e "$BACKUP/$l" ] && [ -n "$l" ]
		then
			j=0
			while [ -e "$BACKUP/$lback/" ]
			do
				let j=j+1
				echo "$BACKUP/$lback exists, new backup file"
				BACKUP="$BACKUP/$lback$j"
				echo "$BACKUP/$lback$j new backup"
			done
		fi
		if [ -d $DST/$l ]
		then
			mkdir "$BACKUP/$lback"
			mv "$DST/$l/*" "$BACKUP/$lback"
		else
			mv "$DST/$l" "$BACKUP/$lback"
		fi
		echo "save '$l' to '$BACKUP/$lback'"
	fi
	if [ ! -e "$DST/$l" ]
	then
		if [ "$COPY" == 0 ]
		then
			ln -fs "$SRC/$f" "$DST/$l"
			echo "link created : $l -> $f "
		else
			# rsync -vh --archive --progress --whole-file "$SRC/$f" "$DST/$l"
			\cp -r "$SRC/$f" "$DST/$l"
			echo "copied: $l -> $f "
		fi
	fi
	let i=i+1
done
