#!/bin/bash
#links files from FILES to their provided LINK

GITURL=https://github.com/Biggybi/dotfiles
SRC=$HOME/dotfiles
DST=$HOME
BACKUP=$HOME/dotfiles/dots_back/

# the links on your machine
FILES=(vim
	vimrc
	bashrc
	bash_aliases
	inputrc
	bin)

# the git files you want on your machine
LINK=(.vim
	.vimrc
	.bashrc
	.bash_aliases
	.inputrc
	bin/)

# the links on your Mac
if [[ "$OSTYPE" == "darwin"* ]]
then
	LINK=(vim
		.vimrc
		.bash_profile
		.bash_aliases
		.inputrc
		.bin/)
fi

if [ -d $SRC ]
then
	echo "Not cloning : $SRC exists"
else
	git clone $GITURL $SRC
fi

if [[ $1 == "--git" ]] || [[ $1 == "-g" ]] || [[ $1 == "--plugins" ]]
then
	echo "Cloning plugins"
	cd ${LINK[0]}
	git submodule init
	git submodule update
else
	echo "Plugin already installed"
fi

i=0
for f in "${FILES[@]}"
do
	l=${LINK[i]}
	echo "$i $l"
	if [ -e $SRC/$f ]
	then
		if [ -L $DST/$l ]
		then
			echo "link deleted : $l"
			#rm $DST/$l
		elif [ -f $DST/$l ]
		then
			[ ! -d $BACKUP ] && mkdir $BACKUP
			mv $DST/$l $BACKUP/$l
			echo "file saved : $BACKUP $l"
		elif [ -d $DST/$l ]
		then
			[ ! -d $BACKUP ] && mkdir $BACKUP
			mv $DST/$l $BACKUP/$l
			echo "file saved : $BACKUP $l"
		fi
		ln -fs $SRC/$f $DST/$l
		echo "link created : $l -> $f "
	else
		echo "no such file : $l"
	fi
	let i=i+1
done
