#!/bin/bash
#links files from FILES to their provided LINK

GITURL=https://github.com/Biggybi/dotfiles
SRC=~/.dotfiles
DST=~
BACKUP=~/.dotfiles/dots_back

FILES=(.vim
	.vimrc
	.bashrc
	.bash_aliases
	.bin)

LINK=(.vim
	.vimrc
	.bashrc
	.bash_aliases
	.bin)

if [[ "$OSTYPE" == "darwin"* ]]
then
	LINK=(.vim
		.vimrc
		.bash_profile
		.bash_aliases
		.bin)
fi

if [ -d $SRC ]
then
	echo "Not cloning : $SRC exists"
else
	git clone $GITURL $SRC
fi

if [[ $1 == "--git" ]] || [[ $1 == "-g" ]] || [[ $1 == "--plugins" ]]
then
	echo "Cloning plugins"
	cd ${LINK[0]}
	git submodule init
	git submodule update
else
	echo "Plugin already installed"
fi

i=0
for f in "${FILES[@]}"
do
	l=${LINK[i]}
	echo "$i $l"
	if [ -e $SRC/$l ]
	then
		if [ -L $DST/$l ]
		then
			echo "link deleted : $l"
			#rm $DST/$l
		elif [ -f $DST/$l ]
		then
			mv $DST/$l $BACKUP
			echo "file saved : $BACKUP $l"
		elif [ -d $DST/$l ]
		then
			mv $DST/$l $BACKUP/$l
			echo "file saved : $BACKUP $l"
		fi
		ln -fs $SRC/$f $DST/$l
		echo "link created : $l -> $f "
	else
		echo "no such file : $l"
	fi
	let i=i+1
done
rm $SRC/.bin/.bin
rm $SRC/.vim/.vim
