#!/bin/bash

T1=093000
T2=190000
B1="the dark side of the moon wallpaper grey.jpeg"
B2="fond ecran ubuntu noir.png"

P="/home/tris/Pictures/Wallpaper/"

NIGHT="$Pdark/"
DAY="$Pdark/"

if [ $1 == "day" ] || [ $1 == "d" ]
then
	gsettings set org.gnome.desktop.interface gtk-theme "Materia-light"
	gsettings set org.gnome.shell.extensions.user-theme name "Materia-light"
	 sed -i '/^alias fzf=/s/dark/light/' $HOME/.bash_aliases
	exit
fi

if [ $1 == 'night' ] || [ $1 == 'n' ]
then
	gsettings set org.gnome.desktop.interface gtk-theme "Materia-dark"
	gsettings set org.gnome.shell.extensions.user-theme name "Materia-dark"
# 	sed -i 's/fzf --color=".*"/fzf --color="dark"/' $HOME/.bashrc
	 sed -i '/^alias fzf=/s/light/dark/' $HOME/.bash_aliases
# 	sed -i 's/fzf --color="light"/fzf --color="dark"/' $HOME/.bashrc
	exit
fi

while [[ 1 ]]
do
	F="0"
	F2="0"
	TIME=$(date +%H%M%S)
	echo background=$F

	if (( $((10#$TIME)) >= $((10#$T1)) && $((10#$TIME)) < $((10#$T2)) ))
	then
		MOMENT=day
		echo "Morning!"
		F="$P$B1"
		D="$DAY"
	else
		MOMENT=night
		echo "Night!"
		F="$P$B2"
	fi

	if [[ $MOD == random ]]
	then
		echo "Random mod"
		D=$(find $D -type f | shuf -n 1)
	fi

	if [[ $MOMENT == day ]]
	then
		#gsettings set org.gnome.desktop.wm.preferences theme "Materia-light"
		gsettings set org.gnome.desktop.interface gtk-theme "Materia-light"
		gsettings set org.gnome.shell.extensions.user-theme name "Materia-light"
		cp ~/.dotfiles/gnome_setup/epiphany/light-stylesheet.css \
			~/.local/share/epiphany/user-stylesheet.css
	else
		#gsettings set org.gnome.desktop.wm.preferences theme "Materia-dark"
		gsettings set org.gnome.desktop.interface gtk-theme "Materia-dark"
		gsettings set org.gnome.shell.extensions.user-theme name "Materia-dark"
		cp ~/.dotfiles/gnome_setup/epiphany/dark-stylesheet.css \
			~/.local/share/epiphany/user-stylesheet.css
	fi

	if [[ $F != $F2 ]]
	then
		echo "New background"
		gsettings set org.gnome.desktop.background picture-uri "$F"
	fi
	F2=$F
	sleep 60 &
	wait
done
