#!/bin/bash

MOD=
T1=100000
T2=190000
B1="the dark side of the moon wallpaper grey.jpeg"
B2="fond ecran ubuntu noir.png"

P="/home/tris/Pictures/Wallpaper/"
NIGHT="$Pdark/"
DAY="$Pdark/"

while [[ 1 ]]
do
	F="0"
	F2="0"
	TIME=$(date +%H%M%S)
	echo background=$F

	if (( $((10#$TIME)) >= $((10#$T1)) && $((10#$TIME)) < $((10#$T2)) ))
	then
		MOMENT=day
		echo "Morning!"
		F="$P$B1"
		D="$DAY"
	else
		MOMENT=night
		echo "Night!"
		F="$P$B2"
	fi
    :q
    :q

	if [[ $MOD == random ]]
	then
		echo "Random mod"
		D=$(find $D -type f | shuf -n 1)
	fi

	if [[ $MOMENT == day ]]
	then
# 		echo day moment=$MOMENT
		gsettings set org.gnome.desktop.wm.preferences theme "Materia-light"
		gsettings set org.gnome.desktop.interface gtk-theme "Materia-light"
	else
# 		echo night moment=$MOMENT
		gsettings set org.gnome.desktop.wm.preferences theme "Materia-dark"
		gsettings set org.gnome.desktop.interface gtk-theme "Materia-dark"
	fi

	if [[ $F != $F2 ]]
	then
		echo "New background"
		gsettings set org.gnome.desktop.background picture-uri "$F"
	fi
	F2=$F
	sleep 60 &
	wait
done
gsettings set org.gnome.desktop.interface gtk-theme Materia-light
