#!/bin/sh

theme="tokyonight_day"
echo "$theme" > ~/.config/onehalf-theme
export FZF_DEFAULT_OPTS="--color='light,bg+:#c4c8da,hl:#f52a65,hl+:#f52a65'"

# tokyonight_moon colors:
# $HOME/.local/share/nvim/lazy/tokyonight.nvim/extras/lua/tokyonight_moon.lua
#
# bk="#e1e2e7" -- bg
# rd="#f52a65" -- red
# gn="#587539" -- green
# yw="#8c6c3e" -- yellow
# be="#2e7de9" -- blue
# pe="#7847bd" -- purple
# ma="#9854f1" -- magenta
# we="#3760bf" -- fg
# g1="#c4c8da" -- bg_highlight
# g2="#a8aecb" -- fg_gutter
# g3="#92a6d5" -- blue7
# g4="#8990b3" -- dark3
# g5="#68709a" -- dark5

color00="22/24/36" # Base 00 - black
color01="f5/2a/65" # Base 08 - red
color02="58/75/39" # Base 0B - green
color03="8c/6c/3e" # Base 0A - yellow
color04="2e/7d/e9" # Base 0D - blue
color05="98/54/f1" # Base 0E - magenta
color06="00/6a/83" # Base 0C - cyan
color07="e1/e2/e7" # Base 05 - white
color08="c4/c8/da" # Base 03 - bright black
color09=$color01   # Base 08 - bright red
color10=$color02   # Base 0B - bright green
color11=$color03   # Base 0A - bright yellow
color12=$color04   # Base 0D - bright blue
color13=$color05   # Base 0E - bright magenta
color14=$color06   # Base 0C - bright cyan
color15="61/72/b0" # Base 07 - bright white
color16="b1/5c/00" # Base 09 - orange
color17="c6/43/43" # Base 0F - red
color18="a8/ae/cb" # Base 01
color19="92/a6/d5" # Base 02
color20="89/90/b3" # Base 04
color21="68/70/9a" # Base 06
color_foreground=$color06 # Base 05
color_background=$color07 # Base 00

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' $@; }
  tmux source-file $DOT/tmux/colors/$theme
# elif [ "${TERM%%[-.]*}" = "screen" ]; then
#   # GNU screen (screen, screen-256color, screen-256color-bce)
#   put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' $@; }
#   put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' $@; }
#   put_template_custom() { printf '\033P\033]%s%s\007\033\\' $@; }
# elif [ "${TERM%%-*}" = "linux" ]; then
#   put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }
#   put_template_var() { true; }
#   put_template_custom() { true; }
else
  put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
  put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
  put_template_custom() { printf '\033]%s%s\033\\' $@; }
fi

# 16 color space
put_template 0  $color_background
put_template 1  $color01
put_template 2  $color02
put_template 3  $color03
put_template 4  $color04
put_template 5  $color05
put_template 6  $color06
put_template 7  $color_foreground
put_template 8  $color08
put_template 9  $color09
put_template 10 $color10
put_template 11 $color11
put_template 12 $color12
put_template 13 $color13
put_template 14 $color14
put_template 15 $color15

# 256 color space
put_template 16 $color16
put_template 17 $color17
put_template 18 $color18
put_template 19 $color19
put_template 20 $color20
put_template 21 $color21

put_template_var 10 $color_foreground
if [ "$BASE16_SHELL_SET_BACKGROUND" != false ]; then
	put_template_var 11 $color_background
	if [ "${TERM%%-*}" = "rxvt" ]; then
		put_template_var 708 $color_background # internal border (rxvt)
	fi
fi
put_template_custom 12 ";7" # cursor (reverse video)

# clean up
unset -f put_template
unset -f put_template_var
unset -f put_template_custom
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background


