#!/bin/bash
theme=$1
echo "$theme" > ~/.config/onehalftheme

if [ -n "$TMUX" ]; then

	put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' $@; }
	put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' $@; }
	put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' $@; }

	# put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
	# put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
	# put_template_custom() { printf '\033]%s%s\033\\' $@; }

	tmux source-file $DOT/tmux/colors/$theme
elif [ "${TERM%%[-.]*}" = "screen" ]; then
	# GNU screen (screen, screen-256color, screen-256color-bce)
	put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' $@; }
	put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' $@; }
	put_template_custom() { printf '\033P\033]%s%s\007\033\\' $@; }
elif [ "${TERM%%-*}" = "linux" ]; then
	put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }
	put_template_var() { true; }
	put_template_custom() { true; }
else
	put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
	put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
	put_template_custom() { printf '\033]%s%s\033\\' $@; }
fi

shift
colors=("$@")
# echo "colors = " ${colors[@]}
# echo "color[] = " ${colors[0]}

i=0
for color in ${colors[@]} ; do
	put_template $i $color
	((i+=1))
done
put_template_var 10 ${colors[7]} # background
put_template_var 11 ${colors[0]} # foreground
if [ "${TERM%%-*}" = "rxvt" ]; then
	put_template_var 708 ${color[7]} # internal border (rxvt)
fi
put_template_custom 14 ";7" # cursor (reverse video)
