#!/bin/bash

bk="#383a42"
rd="#e45649"
gn="#50a14f"
yw="#c18401"
be="#0184bc"
pe="#a626a4"
ma="#0997b3"
we="#E0E0E0"

g5="#a0a1a7"
g4="#c1c1c1"
g3="#d4d4d4"
g2="#e5e5e5"
g1="#f0f0f0"

fg=${bk}
bg=${we}

set -g status-left '#{?client_prefix,#[fg='$bg' bg='$yw'],#[fg='$fg' bg=#'$g3']} #S '
set -g window-style fg="$fg,"bg="$bg"
set -g window-active-style fg="$fg,"bg="$bg"
set -g status-style fg="$fg,"bg="$bg"
set -g window-status-style fg="$g5,"bg="$bg"
set -g window-status-current-format '#{?window_zoomed_flag,#[fg=#'$yw' #bg='$bg' bold],#[fg=#'$fg' #bg='$bg' bold]} #I #W'
set -g window-status-current-style fg="$fg,"bg="$bg"
set -g pane-active-border-style fg="$g5,"bg="$bg"
set -g pane-border-style fg="$g3,"bg="$bg"
