#!/bin/sh
# set -e
# PATH="/usr/local/bin:$PATH"
# dir="`git rev-parse --git-dir`"
# trap 'rm -f "$dir/$$.tags"' EXIT
# git ls-files | \
#   ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
# mv "$dir/$$.tags" "$dir/tags"
# ctags -R -f $dir/tags $dir/../

# dir=$(git rev-parse --git-dir)
# ctags-exuberant -R -f $dir/etags $dir/../
# ctags -R -f $dir/tags $dir/../

#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir=$(git rev-parse --git-dir)
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags-exuberant --tag-relative -L - -f"$dir/$$.tags" --languages=-c
#   ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-c
mv "$dir/$$.tags" "$dir/tags"
