#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT

filelist="$(git ls-files --recurse-submodules)"
ctags --tag-relative=yes -f $dir/$$tags $filelist
