#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
# git ls-files | ctags-exuberant --tag-relative -f"$dir/$$.tags"
git ls-files | \
	ctags-universal --tag-relative=yes -L - -f"$dir/$$.tags"
# git ls-files | \
#   ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-c
mv "$dir/$$.tags" "$dir/tags"
